POST http://localhost:9090/register
Content-Type: application/json

{
  "name": "Vedan",
  "email": "vedant@gmail.com",
  "password": "123456",
  "username": "vedant"
}

###
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "vedant@gmail.com",
  "password": "123456"
}

###
POST http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
  "token":"5fd725ce59ff9d4b31732d43e4294bf3178c693fe4542848be993f6f335c29f6"
}

###
GET http://localhost:9090/user/getAllUserProfile










